### ISSUE TITLE
non-raw pty

### ISSUE THREAD

**Issue by aep** [pkgw/stund#18]
I'm trying to use this to implement an ssh-like thing. The pty must NOT be set to raw mode.
Any opinion on an api that doesnt do that?

**Comment by pkgw** [comment]
I am happy to add one! If I'm recalling correctly, I think it should be pretty straightforward to do so. Would you be able to put together a PR to add such an API?

**Comment by aep** [comment]
yup. let me know if you have better naming ideas.
